"""Tests for the canonical V4 protocol identifiers (T010).

The PoolId vectors in ``tests/fixtures/protocol/pool_id_vectors.json``
were generated by the independent Solidity oracle under
``tools/oracle/`` (Foundry + Solidity 0.8.26 against Uniswap/v4-core).
This test must always agree with that oracle — when the oracle is
re-run, the JSON fixture must be regenerated and committed alongside
the change.

Coverage:

- Address: zero address; non-zero; range enforcement; hex round-trip.
- Currency: native sentinel; ordering invariant; equality.
- ChainId: positive integer only.
- PoolKey: currency ordering; fee bounds; dynamic-fee sentinel;
  tick-spacing bounds; hook address.
- PoolId: bytes32 round-trip; hex round-trip; integer round-trip.
- ABI encoding: 5 × 32 = 160 bytes; field ordering.
- PoolId derivation: matches every pinned vector exactly.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from robinhood_lp.protocol import (
    Address,
    ChainId,
    Currency,
    PoolId,
    PoolKey,
    encode_pool_key,
)

VECTORS = json.loads(
    (Path(__file__).parent / "fixtures" / "protocol" / "pool_id_vectors.json").read_text()
)


# ---------------------------------------------------------------------------
# Address
# ---------------------------------------------------------------------------


def test_address_zero() -> None:
    a = Address.zero()
    assert a.value == 0
    assert a.to_hex() == "0x" + "0" * 40
    assert a.to_bytes() == b"\x00" * 20


def test_address_from_hex_round_trip() -> None:
    raw = 0x1234567890ABCDEF1234567890ABCDEF12345678
    s = "0x" + raw.to_bytes(20, "big").hex()
    a = Address.from_hex(s)
    assert a.value == raw
    assert a.to_hex() == s.lower()


def test_address_from_hex_accepts_mixed_case() -> None:
    raw = 0xABCDEF1234567890ABCDEF1234567890ABCDEF12
    mixed = "0xAbCdEf1234567890aBcDeF1234567890ABCDEF12"
    assert Address.from_hex(mixed).value == raw


def test_address_rejects_overflow() -> None:
    with pytest.raises(ValueError, match="160-bit"):
        Address(1 << 160)


def test_address_rejects_negative() -> None:
    with pytest.raises(ValueError, match="non-negative"):
        Address(-1)


def test_address_from_hex_rejects_wrong_length() -> None:
    with pytest.raises(ValueError):
        Address.from_hex("0x1234")
    with pytest.raises(ValueError):
        Address.from_hex("1234567890abcdef1234567890abcdef12345678")  # no 0x


def test_address_equality_and_hash_use_bytes_only() -> None:
    raw = 0xABABABABABABABABABABABABABABABABABABABAB
    a1 = Address.from_hex("0xabababababababababababababababababababab")
    a2 = Address(raw)
    assert a1 == a2
    assert hash(a1) == hash(a2)


# ---------------------------------------------------------------------------
# Currency
# ---------------------------------------------------------------------------


def test_currency_native_is_zero_address() -> None:
    assert Currency.native().is_native() is True
    assert Currency.native().to_address().value == 0


def test_currency_non_native_is_not_native() -> None:
    c = Currency.from_int(0x20)
    assert c.is_native() is False


def test_currency_address_round_trip() -> None:
    addr = Address.from_hex("0x" + "11" * 20)
    c = Currency.from_address(addr)
    assert c.to_address() == addr


# ---------------------------------------------------------------------------
# ChainId
# ---------------------------------------------------------------------------


def test_chain_id_must_be_positive() -> None:
    with pytest.raises(ValueError, match="positive"):
        ChainId(0)
    with pytest.raises(ValueError, match="positive"):
        ChainId(-1)


def test_chain_id_accepts_positive_integers() -> None:
    assert ChainId(1).value == 1
    assert ChainId(46630).value == 46630


# ---------------------------------------------------------------------------
# PoolKey structural validation
# ---------------------------------------------------------------------------


def _key(
    c0: int = 0x10,
    c1: int = 0x20,
    fee: int = 3000,
    tick: int = 60,
    hooks: int = 0,
) -> PoolKey:
    return PoolKey(
        currency0=Currency.from_int(c0),
        currency1=Currency.from_int(c1),
        fee=fee,
        tick_spacing=tick,
        hooks=Address(hooks),
    )


def test_pool_key_default_construction_is_valid() -> None:
    pk = _key()
    assert pk.currency0.address.value == 0x10
    assert pk.currency1.address.value == 0x20


def test_pool_key_rejects_currency_ordering_violation() -> None:
    with pytest.raises(ValueError, match="strictly less"):
        _key(c0=0x20, c1=0x10)
    with pytest.raises(ValueError, match="strictly less"):
        _key(c0=0x10, c1=0x10)


def test_pool_key_rejects_fee_above_max_and_not_sentinel() -> None:
    with pytest.raises(ValueError, match="invalid"):
        _key(fee=1_000_001)
    with pytest.raises(ValueError, match="160-bit|24-bit|overflow|exceeds"):
        _key(fee=1 << 24)  # overflow uint24


def test_pool_key_accepts_dynamic_fee_sentinel() -> None:
    pk = _key(fee=0x800000)
    assert pk.fee == 0x800000


def test_pool_key_rejects_zero_tick_spacing() -> None:
    with pytest.raises(ValueError, match="tick_spacing"):
        _key(tick=0)


def test_pool_key_rejects_tick_spacing_over_max() -> None:
    with pytest.raises(ValueError, match="tick_spacing"):
        _key(tick=32_768)


def test_pool_key_accepts_max_tick_spacing() -> None:
    pk = _key(tick=32_767)
    assert pk.tick_spacing == 32_767


def test_pool_key_accepts_negative_tick_spacing_in_range() -> None:
    # int24 spans [-2^23, 2^23). Tick spacing cannot be negative per
    # V4 spec (we enforce > 0) but the int24 range is valid to encode.
    with pytest.raises(ValueError, match="tick_spacing"):
        _key(tick=-1)


# ---------------------------------------------------------------------------
# ABI encoding
# ---------------------------------------------------------------------------


def test_encode_pool_key_is_160_bytes() -> None:
    encoded = encode_pool_key(_key())
    assert len(encoded) == 160


def test_encode_pool_key_field_order() -> None:
    """First 32 bytes encode currency0; last 32 bytes encode hooks."""
    pk = _key(c0=0x10, c1=0x20, fee=3000, tick=60, hooks=0x80)
    encoded = encode_pool_key(pk)
    assert int.from_bytes(encoded[0:32], "big") == 0x10  # currency0
    assert int.from_bytes(encoded[32:64], "big") == 0x20  # currency1
    assert int.from_bytes(encoded[64:96], "big") == 3000  # fee
    # tick_spacing is int24 (positive), so two's-complement equals
    # the unsigned representation
    assert int.from_bytes(encoded[96:128], "big", signed=True) == 60
    assert int.from_bytes(encoded[128:160], "big") == 0x80  # hooks


def test_encode_pool_key_sign_extends_negative_int24() -> None:
    """An int24 negative value must be sign-extended in slot 4.

    We exercise the encoding path through encode_pool_key; the
    PoolKey model refuses negative tick_spacing above, so we
    construct the encoding manually via _slot_int to verify
    two's-complement behaviour.
    """
    from robinhood_lp.protocol.abi import _slot_int

    assert _slot_int(-1).hex() == "f" * 64
    assert _slot_int(60).hex() == (60).to_bytes(32, "big").hex()
    assert _slot_int(-2_000_000).hex() == (-2_000_000).to_bytes(32, "big", signed=True).hex()


# ---------------------------------------------------------------------------
# PoolId: bytes32 / hex / int round-trip
# ---------------------------------------------------------------------------


def test_pool_id_from_bytes_requires_32_bytes() -> None:
    with pytest.raises(ValueError, match="32 bytes"):
        PoolId.from_bytes(b"\x00" * 31)
    with pytest.raises(ValueError, match="32 bytes"):
        PoolId.from_bytes(b"\x00" * 33)


def test_pool_id_hex_round_trip() -> None:
    # 63 hex chars = 252 bits, strictly less than 2^256.
    # PoolId.to_hex pads to a full 32-byte (64-hex) representation,
    # so the expected hex is left-padded with a single '0'.
    raw_hex = "deadbeefcafebabe1234567890abcdef0112233445566778899aabbccddeeff"
    p = PoolId(int(raw_hex, 16))
    assert p.to_hex() == "0x0" + raw_hex
    assert PoolId.from_hex(p.to_hex()) == p


def test_pool_id_int_round_trip() -> None:
    raw = 1 << 255
    p = PoolId(raw)
    assert p.value == raw


# ---------------------------------------------------------------------------
# PoolId derivation — exact match against pinned Solidity vectors
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "vector",
    VECTORS["vectors"],
    ids=[v["name"] for v in VECTORS["vectors"]],
)
def test_pool_id_matches_pinned_solidity_vector(vector: dict[str, Any]) -> None:
    """The Python PoolId must match the Solidity oracle for every vector.

    The 'reordered_inputs' vector is special: the Solidity oracle
    sorts its inputs internally (see PoolIdOracle.sol) and produces
    the canonical PoolId, while Python refuses unsorted construction
    by design. We delegate that case to a dedicated test below; here
    we skip it.
    """
    c0 = int(vector["currency0"], 16)
    c1 = int(vector["currency1"], 16)
    if c0 >= c1:
        pytest.skip(
            f"vector {vector['name']!r} supplies unsorted currencies; "
            f"see test_reordered_inputs_refused_by_python_invariant"
        )

    pk = PoolKey(
        currency0=Currency.from_hex(vector["currency0"]),
        currency1=Currency.from_hex(vector["currency1"]),
        fee=int(vector["fee"]),
        tick_spacing=int(vector["tick_spacing"]),
        hooks=Address.from_hex(vector["hooks"]),
    )
    derived = pk.to_pool_id()
    expected_hex = str(vector["expected_pool_id"])
    assert derived.to_hex() == expected_hex, (
        f"vector {vector['name']!r}: Python PoolId {derived.to_hex()} "
        f"!= Solidity oracle {expected_hex}"
    )


def test_reordered_inputs_refused_by_python_invariant() -> None:
    """The 'reordered_inputs' vector exercises the Solidity oracle's
    internal sort. Python refuses unsorted construction; that refusal
    *is* the invariant. The Solidity oracle confirms that the sorted
    form produces PoolId 0xb7a0fb...8fcf2 (same as 'v1_static_3000_60').
    """
    reordered = next(v for v in VECTORS["vectors"] if v["name"] == "reordered_inputs")
    with pytest.raises(ValueError, match="strictly less"):
        PoolKey(
            currency0=Currency.from_hex(reordered["currency0"]),
            currency1=Currency.from_hex(reordered["currency1"]),
            fee=reordered["fee"],
            tick_spacing=reordered["tick_spacing"],
            hooks=Address.from_hex(reordered["hooks"]),
        )

    # And the *sorted* form (the only constructible form) hashes to the
    # same PoolId the Solidity oracle emits for the reordered inputs.
    pk = PoolKey(
        currency0=Currency.from_hex("0x" + "00" * 19 + "10"),
        currency1=Currency.from_hex("0x" + "00" * 19 + "20"),
        fee=3000,
        tick_spacing=60,
        hooks=Address.zero(),
    )
    assert pk.to_pool_id().to_hex() == reordered["expected_pool_id"]


def test_equality_yields_identical_pool_id() -> None:
    """Two PoolKeys equal in every field produce the same PoolId.

    The Solidity oracle already exercises the "reordered inputs"
    case (vector 'reordered_inputs' equals 'v1_static_3000_60');
    here we confirm Python's equality on the canonical (already-sorted)
    form.
    """
    a = PoolKey(
        currency0=Currency.from_int(0x10),
        currency1=Currency.from_int(0x20),
        fee=3000,
        tick_spacing=60,
        hooks=Address.zero(),
    )
    b = PoolKey(
        currency0=Currency.from_int(0x10),
        currency1=Currency.from_int(0x20),
        fee=3000,
        tick_spacing=60,
        hooks=Address.zero(),
    )
    assert a == b
    assert a.to_pool_id() == b.to_pool_id()
