"""Tests for the V4 math port (T012).

Vectors are loaded from ``tests/fixtures/protocol/math_vectors.json``,
which was generated by the Foundry oracle under ``tools/oracle/``.
Every Python output must match the pinned Solidity output exactly.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from robinhood_lp.protocol import (
    MAX_SQRT_PRICE_X96,
    MAX_TICK,
    MIN_SQRT_PRICE_X96,
    MIN_TICK,
    InvalidSqrtPriceError,
    InvalidTickError,
    get_amount0_delta,
    get_amount1_delta,
    get_liquidity_for_amounts,
    get_sqrt_price_at_tick,
    get_tick_at_sqrt_price,
    max_usable_tick,
    min_usable_tick,
)

VECTORS = json.loads(
    (Path(__file__).parent / "fixtures" / "protocol" / "math_vectors.json").read_text()
)


def _u(s: str) -> int:
    """Parse a uint literal that may be written in decimal or hex."""
    return int(s, 16) if s.startswith("0x") else int(s)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------


def test_constants_match_oracle() -> None:
    c = VECTORS["constants"]
    assert c["MIN_TICK"] == MIN_TICK
    assert c["MAX_TICK"] == MAX_TICK
    assert _u(c["MIN_SQRT_PRICE_X96"]) == MIN_SQRT_PRICE_X96
    assert _u(c["MAX_SQRT_PRICE_X96"]) == MAX_SQRT_PRICE_X96


# ---------------------------------------------------------------------------
# getSqrtPriceAtTick
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "vector",
    VECTORS["tick_to_sqrt_price"],
    ids=[v["name"] for v in VECTORS["tick_to_sqrt_price"]],
)
def test_get_sqrt_price_at_tick_matches_oracle(vector: dict[str, Any]) -> None:
    assert get_sqrt_price_at_tick(vector["tick"]) == _u(vector["sqrt_price_x96"])


# ---------------------------------------------------------------------------
# getTickAtSqrtPrice
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "vector",
    VECTORS["sqrt_price_to_tick"],
    ids=[v["name"] for v in VECTORS["sqrt_price_to_tick"]],
)
def test_get_tick_at_sqrt_price_matches_oracle(vector: dict[str, Any]) -> None:
    assert get_tick_at_sqrt_price(_u(vector["sqrt_price_x96"])) == vector["tick"]


# ---------------------------------------------------------------------------
# Domain validation
# ---------------------------------------------------------------------------


def test_get_sqrt_price_at_tick_rejects_above_max() -> None:
    with pytest.raises(InvalidTickError):
        get_sqrt_price_at_tick(MAX_TICK + 1)


def test_get_sqrt_price_at_tick_rejects_below_min() -> None:
    with pytest.raises(InvalidTickError):
        get_sqrt_price_at_tick(MIN_TICK - 1)


def test_get_tick_at_sqrt_price_rejects_below_min() -> None:
    with pytest.raises(InvalidSqrtPriceError):
        get_tick_at_sqrt_price(MIN_SQRT_PRICE_X96 - 1)


def test_get_tick_at_sqrt_price_rejects_at_max() -> None:
    """V4 is strict: sqrtPriceX96 >= MAX_SQRT_PRICE reverts."""
    with pytest.raises(InvalidSqrtPriceError):
        get_tick_at_sqrt_price(MAX_SQRT_PRICE_X96)


def test_get_tick_at_sqrt_price_accepts_max_minus_one() -> None:
    """MAX_SQRT_PRICE - 1 is the largest valid input."""
    assert get_tick_at_sqrt_price(MAX_SQRT_PRICE_X96 - 1) == MAX_TICK - 1


# ---------------------------------------------------------------------------
# Tick monotonicity
# ---------------------------------------------------------------------------


def test_get_sqrt_price_at_tick_is_strictly_monotonic() -> None:
    """Larger ticks must yield larger sqrt prices (positive relationship)."""
    ticks = [-200_000, -100_000, -100, -1, 0, 1, 100, 100_000, 200_000]
    prices = [get_sqrt_price_at_tick(t) for t in ticks]
    for i in range(len(prices) - 1):
        assert prices[i] < prices[i + 1], (
            f"monotonicity violated at "
            f"tick {ticks[i]} ({prices[i]}) -> tick {ticks[i + 1]} ({prices[i + 1]})"
        )


def test_get_tick_at_sqrt_price_is_consistent_with_get_sqrt_price_at_tick() -> None:
    """get_tick(get_sqrt(t)) == t and get_sqrt(get_tick(p)) <= p."""
    test_ticks = [-887_272, -100_000, -100, 0, 100, 100_000, 887_271]
    for t in test_ticks:
        sp = get_sqrt_price_at_tick(t)
        assert get_tick_at_sqrt_price(sp) == t, f"tick={t} not round-tripped"


# ---------------------------------------------------------------------------
# Usable tick helpers
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("spacing", [1, 10, 60, 200, 32_767])
def test_max_usable_tick_aligned(spacing: int) -> None:
    """max_usable_tick(spacing) is the largest tick multiple of spacing <= MAX_TICK."""
    expected = (MAX_TICK // spacing) * spacing
    assert max_usable_tick(spacing) == expected


@pytest.mark.parametrize("spacing", [1, 10, 60, 200, 32_767])
def test_min_usable_tick_aligned(spacing: int) -> None:
    """min_usable_tick(spacing) is the smallest tick multiple of spacing >= MIN_TICK."""
    expected = -((-MIN_TICK) // spacing) * spacing
    assert min_usable_tick(spacing) == expected


# ---------------------------------------------------------------------------
# SqrtPriceMath: amount deltas
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "vector",
    VECTORS["amount_deltas"],
    ids=[v["name"] for v in VECTORS["amount_deltas"]],
)
def test_amount_deltas_match_oracle(vector: dict[str, Any]) -> None:
    pa = _u(vector["sqrt_price_a_x96"])
    pb = _u(vector["sqrt_price_b_x96"])
    liq = _u(vector["liquidity"])
    round_up = vector.get("round_up", False)
    if "amount0" in vector:
        assert get_amount0_delta(pa, pb, liq, round_up=round_up) == _u(vector["amount0"])
    elif "amount1" in vector:
        assert get_amount1_delta(pa, pb, liq, round_up=round_up) == _u(vector["amount1"])
    else:
        pytest.fail(f"vector {vector['name']!r} has neither amount0 nor amount1")


def test_amount_deltas_reject_degenerate_range() -> None:
    """pa must be strictly less than pb (V4 requirement)."""
    p = 79228162514264337593543950336
    with pytest.raises(ValueError):
        get_amount0_delta(p, p, 1)
    with pytest.raises(ValueError):
        get_amount0_delta(p + 1, p, 1)


def test_amount_deltas_reject_overlarge_liquidity() -> None:
    """liquidity must fit in uint128 (V4 enforcement)."""
    p = 79228162514264337593543950336
    with pytest.raises(ValueError):
        get_amount0_delta(p, p + 1, 1 << 128)


# ---------------------------------------------------------------------------
# LiquidityAmounts: round-trip
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "vector",
    VECTORS["liquidity_for_amounts"],
    ids=[v["name"] for v in VECTORS["liquidity_for_amounts"]],
)
def test_liquidity_for_amounts_matches_oracle(vector: dict[str, Any]) -> None:
    p = _u(vector["sqrt_price_x96"])
    pa = _u(vector["sqrt_price_a_x96"])
    pb = _u(vector["sqrt_price_b_x96"])
    a0 = _u(vector["amount0"])
    a1 = _u(vector["amount1"])
    assert get_liquidity_for_amounts(p, pa, pb, a0, a1) == _u(vector["liquidity"])


def test_liquidity_for_amounts_rejects_price_outside_range() -> None:
    """Current price must satisfy pa <= sqrt_price_x96 <= pb."""
    p = 79228162514264337593543950336  # 2^96
    pa = p - 1
    pb = p + 1
    # Below pa (strictly less than pa)
    with pytest.raises(ValueError):
        get_liquidity_for_amounts(pa - 1, pa, pb, 1, 1)
    # Above pb (strictly greater than pb)
    with pytest.raises(ValueError):
        get_liquidity_for_amounts(pb + 1, pa, pb, 1, 1)


# ---------------------------------------------------------------------------
# One-sided liquidity behavior (pinned by Foundry oracle's `a2l/asymmetric_*`)
# ---------------------------------------------------------------------------


def test_liquidity_for_amounts_one_sided_zero_returns_zero() -> None:
    """Documented V4 behavior: one-sided liquidityForAmounts with the
    non-contributing side at zero yields zero."""
    p = 79228162514264337593543950336
    pa = 78833030112140176575862854579
    pb = 79625275426524748796330556128
    # Above the range, amount1 contributes nothing; amount0 alone yields
    # the full-side liquidity.
    # Below the range, symmetric.
    # The pinned vectors cover (amount0=0, amount1>0) and (amount1=0,
    # amount0>0); this test pins that round trip behavior.
    liq0_only = get_liquidity_for_amounts(p, pa, pb, 1_000_000_000_000_000_000, 0)
    liq1_only = get_liquidity_for_amounts(p, pa, pb, 0, 1_000_000_000_000_000_000)
    # Both are zero because the V4 implementation returns min(liq0, liq1)
    # where one side is zero — see the `_meta` note in math_vectors.json.
    assert liq0_only == 0
    assert liq1_only == 0
