"""T032 — Capability-driven historical ingestion for a single PoolKey.

This package ties together:

- the range planner (cold-start vs warm-incremental topology,
  one topic0 OR filter, fixed topic1 pool id);
- the preflight probe (per-endpoint capability snapshot + budget
  ledger);
- the A+B router (Robinhood wide-range primary, Alchemy Free
  failover within measured capability and remaining budget);
- the durable checkpoint + retry ledger + run manifest writer;
- the orchestrator runner.

All deliverables from the T032 contract are covered. The package
depends on the T030 decode surface and the T031 storage writer /
manifest store.
"""

from __future__ import annotations

from robinhood_lp.ingestion.capability import (
    DEFAULT_ALCHEMY_MAX_BLOCKS_PER_GET_LOGS,
    DEFAULT_MAX_RESPONSE_BYTES,
    DEFAULT_ROBINHOOD_MAX_BLOCKS_PER_GET_LOGS,
    BudgetSnapshot,
    CapabilitySnapshot,
    EndpointBudget,
    EndpointCapability,
    RemainingBudget,
)
from robinhood_lp.ingestion.checkpoint import (
    EMPTY_CHECKPOINT_HASH,
    DurableCheckpointState,
    load_durable_checkpoint,
    upsert_durable_checkpoint,
)
from robinhood_lp.ingestion.errors import (
    REASON_BUDGET_EXHAUSTED,
    REASON_BUDGET_EXHAUSTED_CALLS,
    REASON_BUDGET_EXHAUSTED_CU,
    REASON_BUDGET_EXHAUSTED_RESPONSE_QUOTA,
    REASON_BUDGET_EXHAUSTED_TIME,
    REASON_CANCELLED_BY_OPERATOR,
    REASON_EMPTY_RESPONSE,
    REASON_HTTP_4XX,
    REASON_HTTP_5XX,
    REASON_HTTP_403_DEFAULT_USER_AGENT,
    REASON_HTTP_403_USER_AGENT_REJECTED,
    REASON_HTTP_429_RATE_LIMIT,
    REASON_INVALID_RESPONSE,
    REASON_NO_CAPABLE_ENDPOINT,
    REASON_OK,
    REASON_RANGE_TOO_LARGE,
    REASON_RESPONSE_SIZE_OVERFLOW,
    REASON_RPC_TIMEOUT,
    REASON_SINGLE_BLOCK_OVERFLOW,
    REASON_SKIPPED_NOT_REQUIRED,
    STATE_CANCELLED,
    STATE_FAILED,
    STATE_SCANNED_EMPTY,
    STATE_SUCCESSFUL,
    TOPOLOGY_COLD_START,
    TOPOLOGY_WARM_INCREMENTAL,
    BudgetExhaustedError,
    CancelledError,
    CheckpointMismatchError,
    IngestionError,
    NoCapableEndpointError,
    is_budget_exhausted_reason,
)
from robinhood_lp.ingestion.planner import (
    REQUIRED_TOPIC0_NAMES,
    ExistingCheckpoint,
    PlannedRun,
    PlannedSubRange,
    RangePlanner,
    RangePlannerInputs,
    build_pool_topic_filter,
    build_topic0_filter,
    split_sub_range,
)
from robinhood_lp.ingestion.probe import (
    DEFAULT_OPERATOR_BUDGET,
    OperatorBudgetInjection,
    PreflightProbe,
    PreflightProbeResult,
    ProbeSource,
)
from robinhood_lp.ingestion.router import (
    ALIAS_ALCHEMY_FREE,
    ALIAS_ROBINHOOD_PUBLIC,
    DEFAULT_FAILOVER_ORDER,
    BudgetLedger,
    CoverageDecision,
    EndpointCallResult,
    EndpointClient,
    Router,
    RouterConfig,
    classify_coverage,
    reason_hint,
    retry_outcome_for_reason,
)
from robinhood_lp.ingestion.runner import (
    CANCELLED_REASON,
    DEFAULT_MAX_BLOCKS_PER_PARTITION,
    BlockHeaderCache,
    BlockHeaderSource,
    CancellationToken,
    IngestionResult,
    IngestionRunner,
)

__all__ = [
    "ALIAS_ALCHEMY_FREE",
    "ALIAS_ROBINHOOD_PUBLIC",
    "BlockHeaderCache",
    "BlockHeaderSource",
    "BudgetExhaustedError",
    "BudgetLedger",
    "BudgetSnapshot",
    "CANCELLED_REASON",
    "CancelledError",
    "CancellationToken",
    "CapabilitySnapshot",
    "CheckpointMismatchError",
    "CoverageDecision",
    "DEFAULT_ALCHEMY_MAX_BLOCKS_PER_GET_LOGS",
    "DEFAULT_FAILOVER_ORDER",
    "DEFAULT_MAX_BLOCKS_PER_PARTITION",
    "DEFAULT_MAX_RESPONSE_BYTES",
    "DEFAULT_OPERATOR_BUDGET",
    "DEFAULT_ROBINHOOD_MAX_BLOCKS_PER_GET_LOGS",
    "DurableCheckpointState",
    "EMPTY_CHECKPOINT_HASH",
    "EndpointBudget",
    "EndpointCallResult",
    "EndpointCapability",
    "EndpointClient",
    "ExistingCheckpoint",
    "IngestionError",
    "IngestionResult",
    "IngestionRunner",
    "NoCapableEndpointError",
    "OperatorBudgetInjection",
    "PlannedRun",
    "PlannedSubRange",
    "PreflightProbe",
    "PreflightProbeResult",
    "ProbeSource",
    "REASON_BUDGET_EXHAUSTED",
    "REASON_BUDGET_EXHAUSTED_CALLS",
    "REASON_BUDGET_EXHAUSTED_CU",
    "REASON_BUDGET_EXHAUSTED_RESPONSE_QUOTA",
    "REASON_BUDGET_EXHAUSTED_TIME",
    "REASON_CANCELLED_BY_OPERATOR",
    "REASON_EMPTY_RESPONSE",
    "REASON_HTTP_403_DEFAULT_USER_AGENT",
    "REASON_HTTP_403_USER_AGENT_REJECTED",
    "REASON_HTTP_429_RATE_LIMIT",
    "REASON_HTTP_4XX",
    "REASON_HTTP_5XX",
    "REASON_INVALID_RESPONSE",
    "REASON_NO_CAPABLE_ENDPOINT",
    "REASON_OK",
    "REASON_RANGE_TOO_LARGE",
    "REASON_RESPONSE_SIZE_OVERFLOW",
    "REASON_RPC_TIMEOUT",
    "REASON_SINGLE_BLOCK_OVERFLOW",
    "REASON_SKIPPED_NOT_REQUIRED",
    "REQUIRED_TOPIC0_NAMES",
    "RangePlanner",
    "RangePlannerInputs",
    "RemainingBudget",
    "Router",
    "RouterConfig",
    "STATE_CANCELLED",
    "STATE_FAILED",
    "STATE_SCANNED_EMPTY",
    "STATE_SUCCESSFUL",
    "TOPOLOGY_COLD_START",
    "TOPOLOGY_WARM_INCREMENTAL",
    "build_pool_topic_filter",
    "build_topic0_filter",
    "classify_coverage",
    "is_budget_exhausted_reason",
    "load_durable_checkpoint",
    "reason_hint",
    "retry_outcome_for_reason",
    "split_sub_range",
    "upsert_durable_checkpoint",
]
