"""Storage layer (T030-T034)."""

from __future__ import annotations

from robinhood_lp.storage.decode_log import LogDecodeContext, decode_log
from robinhood_lp.storage.manifest import (
    MANIFEST_SCHEMA_VERSION,
    AccountingInterval,
    BlockHeaderInconsistencyError,
    ConflictingObservation,
    ManifestStore,
    PartitionBounds,
    PartitionManifestRow,
    PartitionQualification,
    validate_endpoint_alias,
)
from robinhood_lp.storage.measurement import (
    ShortRangeMeasurement,
    assert_measurement_within_tolerance,
    measure_short_range,
)
from robinhood_lp.storage.partition import (
    EVENT_NAMES,
    PartitionKey,
    parquet_schema_for,
)
from robinhood_lp.storage.reader import (
    BoundsMismatchError,
    FutureSchemaError,
    ManifestMismatchError,
    MissingPartitionError,
    PartitionReadResult,
    RawPartitionReader,
    ReaderError,
    UnqualifiedDatasetError,
)
from robinhood_lp.storage.reconciliation import (
    PartitionReconciliationReport,
    event_key_from_partition_key,
    event_key_from_record,
    find_inconsistent_partitions,
    reconcile_all_partitions,
    reconcile_partition,
)
from robinhood_lp.storage.schema import (
    CURRENT_DECODE_VERSION,
    CURRENT_SCHEMA_VERSION,
    AcquisitionProvenance,
    BlockContext,
    DonateLogRecord,
    InitializeLogRecord,
    ModifyLiquidityLogRecord,
    ProtocolFeeUpdatedLogRecord,
    ReceiptContext,
    SwapLogRecord,
    TransactionContext,
    canonical_bytes,
    from_canonical_bytes,
    migrate_to_current,
    normalized_content_hash,
)
from robinhood_lp.storage.writer import (
    DEFAULT_BLOCKS_PER_PARTITION,
    AppendResult,
    RawPartitionWriter,
    SilentRowLossError,
    derive_partition_key,
    records_to_arrow_table,
)

__all__ = [
    "AccountingInterval",
    "AcquisitionProvenance",
    "AppendResult",
    "BlockContext",
    "BlockHeaderInconsistencyError",
    "BoundsMismatchError",
    "CURRENT_DECODE_VERSION",
    "CURRENT_SCHEMA_VERSION",
    "ConflictingObservation",
    "DEFAULT_BLOCKS_PER_PARTITION",
    "DonateLogRecord",
    "EVENT_NAMES",
    "FutureSchemaError",
    "InitializeLogRecord",
    "LogDecodeContext",
    "MANIFEST_SCHEMA_VERSION",
    "ManifestMismatchError",
    "ManifestStore",
    "MissingPartitionError",
    "ModifyLiquidityLogRecord",
    "PartitionBounds",
    "PartitionKey",
    "PartitionManifestRow",
    "PartitionQualification",
    "PartitionReadResult",
    "PartitionReconciliationReport",
    "ProtocolFeeUpdatedLogRecord",
    "RawPartitionReader",
    "RawPartitionWriter",
    "ReaderError",
    "ReceiptContext",
    "ShortRangeMeasurement",
    "SilentRowLossError",
    "SwapLogRecord",
    "TransactionContext",
    "UnqualifiedDatasetError",
    "assert_measurement_within_tolerance",
    "canonical_bytes",
    "decode_log",
    "derive_partition_key",
    "event_key_from_partition_key",
    "event_key_from_record",
    "find_inconsistent_partitions",
    "from_canonical_bytes",
    "manifest",
    "measure_short_range",
    "migrate_to_current",
    "normalized_content_hash",
    "parquet_schema_for",
    "reconcile_all_partitions",
    "reconcile_partition",
    "records_to_arrow_table",
    "validate_endpoint_alias",
]
