"""Data-quality and completeness reports (T034).

The ``robinhood_lp.quality`` package owns the report structure,
reason codes, infrastructure-correlation state, deterministic
cross-provider sample selection (Decision 6), and the verifier that
decides ``complete=true`` vs ``complete=false``.

Downstream code consumes only explicitly qualified datasets; a
dataset without a passing T034 report is not qualified and must not
be loaded.
"""

from __future__ import annotations

from robinhood_lp.quality.infrastructure import (
    CROSS_ENDPOINT_AGREEMENT_PHRASING,
    DEFAULT_INFRASTRUCTURE_CORRELATION_STATE,
    INDEPENDENT_PROVIDER_AGREEMENT_PHRASING,
    InfrastructureCorrelationState,
    agreement_phrasing_for_state,
    correlated_failure_is_residual_risk,
)
from robinhood_lp.quality.quality_report import (
    ActualBudgetEntry,
    BudgetDeviation,
    CapabilityEntry,
    PreflightBudgetEntry,
    ProviderProvenanceEntry,
    QualityFinding,
    QualityReport,
    SharedInfrastructureEvidence,
    TopologyKind,
    VolumeEntry,
    empty_report,
    with_actual_budget,
    with_budget_deviation,
    with_capability_snapshot,
    with_complete,
    with_finding,
    with_infrastructure_state,
    with_preflight_budget,
    with_provider_provenance,
    with_qualification_blocker,
    with_response_volume,
    with_shared_infrastructure_evidence,
)
from robinhood_lp.quality.reason_codes import (
    ALL_REASON_CODES,
    QUALIFICATION_FATAL_REASON_CODES,
    REASON_BLOCK_HASH_GAP,
    REASON_BUDGET_EXHAUSTED,
    REASON_CAPABILITY_REGRESSION,
    REASON_CHECKPOINT_MISMATCH,
    REASON_CROSS_ENDPOINT_SAMPLE_DISAGREE,
    REASON_CROSS_ENDPOINT_SAMPLE_INFRASTRUCTURE_UNCLEAR,
    REASON_CROSS_ENDPOINT_SAMPLE_MISSING,
    REASON_CROSS_PROVIDER_DISCREPANCY,
    REASON_DECODE_ERROR,
    REASON_DUPLICATE_EVENT_KEY,
    REASON_IMPOSSIBLE_VALUE,
    REASON_METADATA_FAILURE,
    REASON_MISORDERED_LOG,
    REASON_RANGE_COVERAGE_GAP,
    REASON_STALE_ENDPOINT,
    REASON_UNKNOWN_POOL,
    REASON_USER_AGENT_REJECTED,
    is_qualification_fatal_reason,
)
from robinhood_lp.quality.sample_selection import (
    WINDOW_BLOCKS,
    PerEventTypeSample,
    PerFailoverSample,
    PerPartitionSample,
    PerRunSample,
    RequiredSamples,
    select_per_event_type_sample,
    select_per_failover_sample,
    select_per_partition_sample,
    select_per_run_sample,
    select_required_samples,
    with_result_bearing_windows,
)
from robinhood_lp.quality.verification import (
    VerificationResult,
    verify_report,
)

__all__ = [
    "ALL_REASON_CODES",
    "ActualBudgetEntry",
    "BudgetDeviation",
    "CROSS_ENDPOINT_AGREEMENT_PHRASING",
    "CapabilityEntry",
    "DEFAULT_INFRASTRUCTURE_CORRELATION_STATE",
    "INDEPENDENT_PROVIDER_AGREEMENT_PHRASING",
    "InfrastructureCorrelationState",
    "PerEventTypeSample",
    "PerFailoverSample",
    "PerPartitionSample",
    "PerRunSample",
    "PreflightBudgetEntry",
    "ProviderProvenanceEntry",
    "QUALIFICATION_FATAL_REASON_CODES",
    "QualityFinding",
    "QualityReport",
    "REASON_BLOCK_HASH_GAP",
    "REASON_BUDGET_EXHAUSTED",
    "REASON_CAPABILITY_REGRESSION",
    "REASON_CHECKPOINT_MISMATCH",
    "REASON_CROSS_ENDPOINT_SAMPLE_DISAGREE",
    "REASON_CROSS_ENDPOINT_SAMPLE_INFRASTRUCTURE_UNCLEAR",
    "REASON_CROSS_ENDPOINT_SAMPLE_MISSING",
    "REASON_CROSS_PROVIDER_DISCREPANCY",
    "REASON_DECODE_ERROR",
    "REASON_DUPLICATE_EVENT_KEY",
    "REASON_IMPOSSIBLE_VALUE",
    "REASON_METADATA_FAILURE",
    "REASON_MISORDERED_LOG",
    "REASON_RANGE_COVERAGE_GAP",
    "REASON_STALE_ENDPOINT",
    "REASON_UNKNOWN_POOL",
    "REASON_USER_AGENT_REJECTED",
    "RequiredSamples",
    "SharedInfrastructureEvidence",
    "TopologyKind",
    "VerificationResult",
    "VolumeEntry",
    "WINDOW_BLOCKS",
    "agreement_phrasing_for_state",
    "correlated_failure_is_residual_risk",
    "empty_report",
    "is_qualification_fatal_reason",
    "select_per_event_type_sample",
    "select_per_failover_sample",
    "select_per_partition_sample",
    "select_per_run_sample",
    "select_required_samples",
    "verify_report",
    "with_actual_budget",
    "with_budget_deviation",
    "with_capability_snapshot",
    "with_complete",
    "with_finding",
    "with_infrastructure_state",
    "with_preflight_budget",
    "with_provider_provenance",
    "with_qualification_blocker",
    "with_response_volume",
    "with_result_bearing_windows",
    "with_shared_infrastructure_evidence",
]
