"""V1 strategy layer public surface (T060 + T062).

The ``robinhood_lp.strategy`` package is the strategy layer per
``docs/spec/architecture/ARCHITECTURE.md`` §2.1: it is a *pure*
observation -> candidate-action function of timestamped state.

The layer depends only on the protocol-domain package (``ids``,
``events``, ``math``, ``sizing``) and the stdlib. It must not
import RPC, storage, configuration, signing, execution, or the
replay layer (the replay output is consumed by the caller, which
packages it into the :class:`MarketSnapshot` and
:class:`PortfolioSnapshot` the strategy reads).

T060 is the *contracts* half of the strategy layer. It defines
the immutable, versioned snapshots the strategy reads; the
substitutable :class:`RegimeModel` and
:class:`FeeOpportunityModel` components with their respective
:class:`RegimeAssessment` and
:class:`FeeOpportunityAssessment` outputs (the sole supported
extension point for a trained model per
``docs/spec/strategy/STRATEGY_ECONOMICS.md`` §7 and ADR-014 §5);
the deterministic :class:`DeterministicClock` and
:class:`SeededRandomSource` interfaces the strategy reads instead
of wall-clock time or unseeded randomness; the tick/capital
proposal validator that rejects invalid ticks, stale state, NaN
display values and excessive capital *before* a candidate action
is constructed; the structured :class:`ReasonCode` vocabulary the
``NO_TRADE`` verdict carries; and the :class:`CandidateAction`
the strategy submits to the central risk and execution layers.
The candidate action is the proposal the strategy submits to
execution; execution constructs the actual transactions.

T062 is the *baseline policies* half. It exports five auditable,
pool-agnostic baseline strategies
(:class:`HoldStrategy`, :class:`BroadRangeStrategy`,
:class:`FixedWidthStrategy`, :class:`VolatilityWidthStrategy`,
:class:`OutOfRangeRebalanceStrategy`) that anchor every later
strategy in the comparison harness.
"""

from __future__ import annotations

from robinhood_lp.strategy.base import (
    ADMISSION_SNAPSHOT_VERSION,
    CANDIDATE_ACTION_VERSION,
    CANDIDATE_KIND_NO_TRADE,
    CANDIDATE_KIND_PROPOSE,
    CANDIDATE_KIND_WAIT,
    CANDIDATE_SENTINEL_LIQUIDITY,
    CANDIDATE_SENTINEL_TICK,
    FEE_OPPORTUNITY_ASSESSMENT_VERSION,
    FEE_OPPORTUNITY_OUTCOME_ASSESSED,
    FEE_OPPORTUNITY_OUTCOME_UNCERTAIN,
    MARKET_SNAPSHOT_VERSION,
    MAX_CAPITAL_Q64_64,
    MAX_TICK_SPACING_STRATEGY,
    MIN_TICK_SPACING_STRATEGY,
    PORTFOLIO_SNAPSHOT_VERSION,
    Q64_SCALE,
    REGIME_ASSESSMENT_VERSION,
    REGIME_OUTCOME_ASSESSED,
    REGIME_OUTCOME_UNCERTAIN,
    REGIME_STATE_DOWN_TREND,
    REGIME_STATE_JUMP_RISK,
    REGIME_STATE_RANGE,
    REGIME_STATE_UNCERTAIN,
    REGIME_STATE_UP_TREND,
    AdmissionSnapshot,
    CandidateAction,
    CandidateActionError,
    DeterministicClock,
    DeterministicClockError,
    FeeOpportunityAssessment,
    FeeOpportunityModel,
    FrozenClock,
    FrozenSeededRandomSource,
    InvalidCapitalError,
    InvalidProposalError,
    InvalidSnapshotError,
    InvalidTickError,
    MarketSnapshot,
    NaNDisplayValueError,
    PortfolioSnapshot,
    ProposalValidationError,
    ReasonCode,
    RegimeAssessment,
    RegimeModel,
    SeededRandomSource,
    StaleSnapshotError,
    StrategyError,
    assert_strategy_layer_is_pure,
    collect_strategy_module_imports,
    evaluate_decision,
    validate_proposal,
)
from robinhood_lp.strategy.baselines import (
    BASELINE_STRATEGY_VERSION,
    DEFAULT_BASELINE_CAPITAL_Q64_64,
    DEFAULT_BASELINE_LIQUIDITY,
    DEFAULT_FIXED_HALF_WIDTH_TICKS,
    DEFAULT_MAX_HALF_WIDTH_TICKS,
    DEFAULT_MIN_HALF_WIDTH_TICKS,
    DEFAULT_REBALANCE_HALF_WIDTH_TICKS,
    DEFAULT_VOLATILITY_MULTIPLIER,
    DEFAULT_VOLATILITY_WINDOW,
    NOTES_BROAD_RANGE_HOLD,
    NOTES_BROAD_RANGE_OPEN,
    NOTES_FIXED_WIDTH_HOLD,
    NOTES_FIXED_WIDTH_OPEN,
    NOTES_FIXED_WIDTH_REBALANCE,
    NOTES_HOLD,
    NOTES_HOLD_INVALID_TICK,
    NOTES_INSUFFICIENT_CAPITAL,
    NOTES_NO_MARKET_DATA,
    NOTES_REBALANCE_HOLD,
    NOTES_REBALANCE_OPEN,
    NOTES_REBALANCE_REBALANCE,
    NOTES_TICKS_OUT_OF_BOUNDS,
    NOTES_VOLATILITY_HOLD,
    NOTES_VOLATILITY_OPEN,
    NOTES_VOLATILITY_REBALANCE,
    BaselineStrategyError,
    BroadRangeStrategy,
    FixedWidthStrategy,
    HoldStrategy,
    InvalidBaselineCapitalError,
    InvalidBaselineTickError,
    OutOfRangeRebalanceStrategy,
    VolatilityWidthStrategy,
    baseline_kind_tag,
)
from robinhood_lp.strategy.registry import (
    IDENTITY_ADAPTIVE_RANGE,
    IDENTITY_BROAD_RANGE,
    IDENTITY_FIXED_WIDTH,
    IDENTITY_HOLD,
    IDENTITY_OUT_OF_RANGE_REBALANCE,
    IDENTITY_VOLATILITY_WIDTH,
    REGISTRY_VERSION,
    CodeProvenance,
    InvalidCodeProvenanceError,
    InvalidParameterSchemaError,
    InvalidParameterValueError,
    ParameterSchema,
    ParameterType,
    RegisteredStrategy,
    Registry,
    RegistryError,
    StrategyFactory,
    UnknownStrategyIdentityError,
    assert_registry_layer_is_pure,
    default_registry,
    is_registered,
    lookup,
    registered_identities,
    registry_checksum,
    reset_default_registry_cache,
    resolve_module_revision,
    validate_parameters,
)

__all__ = [
    "ADMISSION_SNAPSHOT_VERSION",
    "CANDIDATE_ACTION_VERSION",
    "CANDIDATE_KIND_NO_TRADE",
    "CANDIDATE_KIND_PROPOSE",
    "CANDIDATE_KIND_WAIT",
    "CANDIDATE_SENTINEL_LIQUIDITY",
    "CANDIDATE_SENTINEL_TICK",
    "FEE_OPPORTUNITY_ASSESSMENT_VERSION",
    "FEE_OPPORTUNITY_OUTCOME_ASSESSED",
    "FEE_OPPORTUNITY_OUTCOME_UNCERTAIN",
    "MARKET_SNAPSHOT_VERSION",
    "MAX_CAPITAL_Q64_64",
    "MAX_TICK_SPACING_STRATEGY",
    "MIN_TICK_SPACING_STRATEGY",
    "PORTFOLIO_SNAPSHOT_VERSION",
    "Q64_SCALE",
    "REGIME_ASSESSMENT_VERSION",
    "REGIME_OUTCOME_ASSESSED",
    "REGIME_OUTCOME_UNCERTAIN",
    "REGIME_STATE_DOWN_TREND",
    "REGIME_STATE_JUMP_RISK",
    "REGIME_STATE_RANGE",
    "REGIME_STATE_UNCERTAIN",
    "REGIME_STATE_UP_TREND",
    "AdmissionSnapshot",
    "CandidateAction",
    "CandidateActionError",
    "DeterministicClock",
    "DeterministicClockError",
    "FeeOpportunityAssessment",
    "FeeOpportunityModel",
    "FrozenClock",
    "FrozenSeededRandomSource",
    "InvalidCapitalError",
    "InvalidProposalError",
    "InvalidSnapshotError",
    "InvalidTickError",
    "MarketSnapshot",
    "NaNDisplayValueError",
    "PortfolioSnapshot",
    "ProposalValidationError",
    "RegimeAssessment",
    "RegimeModel",
    "ReasonCode",
    "SeededRandomSource",
    "StaleSnapshotError",
    "StrategyError",
    "assert_strategy_layer_is_pure",
    "collect_strategy_module_imports",
    "evaluate_decision",
    "validate_proposal",
    # T062 baselines
    "BASELINE_STRATEGY_VERSION",
    "BroadRangeStrategy",
    "DEFAULT_BASELINE_CAPITAL_Q64_64",
    "DEFAULT_BASELINE_LIQUIDITY",
    "DEFAULT_FIXED_HALF_WIDTH_TICKS",
    "DEFAULT_MAX_HALF_WIDTH_TICKS",
    "DEFAULT_MIN_HALF_WIDTH_TICKS",
    "DEFAULT_REBALANCE_HALF_WIDTH_TICKS",
    "DEFAULT_VOLATILITY_MULTIPLIER",
    "DEFAULT_VOLATILITY_WINDOW",
    "FixedWidthStrategy",
    "HoldStrategy",
    "InvalidBaselineCapitalError",
    "InvalidBaselineTickError",
    "BaselineStrategyError",
    "NOTES_BROAD_RANGE_HOLD",
    "NOTES_BROAD_RANGE_OPEN",
    "NOTES_FIXED_WIDTH_HOLD",
    "NOTES_FIXED_WIDTH_OPEN",
    "NOTES_FIXED_WIDTH_REBALANCE",
    "NOTES_HOLD",
    "NOTES_HOLD_INVALID_TICK",
    "NOTES_INSUFFICIENT_CAPITAL",
    "NOTES_NO_MARKET_DATA",
    "NOTES_REBALANCE_HOLD",
    "NOTES_REBALANCE_OPEN",
    "NOTES_REBALANCE_REBALANCE",
    "NOTES_TICKS_OUT_OF_BOUNDS",
    "NOTES_VOLATILITY_HOLD",
    "NOTES_VOLATILITY_OPEN",
    "NOTES_VOLATILITY_REBALANCE",
    "OutOfRangeRebalanceStrategy",
    "VolatilityWidthStrategy",
    "baseline_kind_tag",
    # T068 strategy registry
    "IDENTITY_ADAPTIVE_RANGE",
    "IDENTITY_BROAD_RANGE",
    "IDENTITY_FIXED_WIDTH",
    "IDENTITY_HOLD",
    "IDENTITY_OUT_OF_RANGE_REBALANCE",
    "IDENTITY_VOLATILITY_WIDTH",
    "REGISTRY_VERSION",
    "CodeProvenance",
    "InvalidCodeProvenanceError",
    "InvalidParameterSchemaError",
    "InvalidParameterValueError",
    "ParameterSchema",
    "ParameterType",
    "RegisteredStrategy",
    "Registry",
    "RegistryError",
    "StrategyFactory",
    "UnknownStrategyIdentityError",
    "assert_registry_layer_is_pure",
    "default_registry",
    "is_registered",
    "lookup",
    "registered_identities",
    "registry_checksum",
    "reset_default_registry_cache",
    "resolve_module_revision",
    "validate_parameters",
]

__version__: str = "0.0.0"
